In [10]:
import pandas as pd
import numpy as np


In [11]:
pip install scipy

     ---------------------------------------- 0.0/42.5 MB ? eta -:--:--
     --------------------------------------- 0.0/42.5 MB 991.0 kB/s eta 0:00:43
     ---------------------------------------- 0.1/42.5 MB 1.3 MB/s eta 0:00:33
     ---------------------------------------- 0.2/42.5 MB 1.4 MB/s eta 0:00:31
     ---------------------------------------- 0.2/42.5 MB 1.5 MB/s eta 0:00:28
     ---------------------------------------- 0.3/42.5 MB 1.3 MB/s eta 0:00:33
     ---------------------------------------- 0.3/42.5 MB 1.4 MB/s eta 0:00:32
     ---------------------------------------- 0.4/42.5 MB 1.3 MB/s eta 0:00:34
     ---------------------------------------- 0.4/42.5 MB 1.2 MB/s eta 0:00:34
     ---------------------------------------- 0.5/42.5 MB 1.3 MB/s eta 0:00:33
      --------------------------------------- 0.6/42.5 MB 1.4 MB/s eta 0:00:31
      --------------------------------------- 0.7/42.5 MB 1.4 MB/s eta 0:00:30
      --------------------------------------- 0.8/42.5 MB 

In [12]:
from scipy import stats

In [2]:
pip install seaborn

     ---------------------------------------- 0.0/293.3 kB ? eta -:--:--
     ---- ----------------------------------- 30.7/293.3 kB ? eta -:--:--
     ------------ -------------------------- 92.2/293.3 kB 1.3 MB/s eta 0:00:01
     ------------ -------------------------- 92.2/293.3 kB 1.3 MB/s eta 0:00:01
     ----------------- ------------------ 143.4/293.3 kB 853.3 kB/s eta 0:00:01
     ----------------------------- -------- 225.3/293.3 kB 1.1 MB/s eta 0:00:01
     -------------------------------------- 293.3/293.3 kB 1.1 MB/s eta 0:00:00
     ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
      --------------------------------------- 0.1/7.6 MB 3.6 MB/s eta 0:00:03
     - -------------------------------------- 0.3/7.6 MB 3.2 MB/s eta 0:00:03
     -- ------------------------------------- 0.4/7.6 MB 2.8 MB/s eta 0:00:03
     -- ------------------------------------- 0.5/7.6 MB 2.7 MB/s eta 0:00:03
     --- ------------------------------------ 0.6/7.6 MB 2.6 MB/s eta 

In [4]:
import seaborn as sns

In [6]:
# Load the dataset
df = pd.read_csv('heart_cleveland_upload.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     69    1   0       160   234    1        2      131      0      0.1   
1     69    0   0       140   239    0        0      151      0      1.8   
2     66    0   0       150   226    0        0      114      0      2.6   
3     65    1   0       138   282    1        2      174      0      1.4   
4     64    1   0       110   211    0        2      144      1      1.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
292   40    1   3       152   223    0        0      181      0      0.0   
293   39    1   3       118   219    0        0      140      0      1.2   
294   35    1   3       120   198    0        0      130      1      1.6   
295   35    0   3       138   183    0        0      182      0      1.4   
296   35    1   3       126   282    0        2      156      1      0.0   

     slope  ca  thal  condition  
0        1   1     0          0  
1        0   2     0          0  
2        2   0     0          0  
3        1   1     0          1  
4        1   0     0          0  
..     ...  ..   ...        ...  
292      0   0     2          1  
293      1   0     2          1  
294      1   0     2          1  
295      0   0     0          0  
296      0   0     2          1  

[297 rows x 14 columns]

In [7]:
# Create a contingency table of sex and heart disease status
#condition: 0 = no disease, 1 = disease
#sex (1 = male; 0 = female)
data_chi=pd.crosstab(df["sex"],df["condition"])
data_chi

condition   0    1
sex               
0          71   25
1          89  112

In [8]:
#Perform the Chi-square test
observedValue=data_chi.values
observedValue

array([[ 71,  25],
       [ 89, 112]], dtype=int64)

In [14]:
value=stats.chi2_contingency(data_chi)
value

Chi2ContingencyResult(statistic=21.851612168613475, pvalue=2.945690038078843e-06, dof=1, expected_freq=array([[ 51.71717172,  44.28282828],
       [108.28282828,  92.71717172]]))

In [15]:
expectedValue=value[3]
expectedValue

array([[ 51.71717172,  44.28282828],
       [108.28282828,  92.71717172]])

In [17]:
chi2=value[0]
p=value[1]
dof=value[2]

In [18]:
# Print the test statistic, p-value, and degrees of freedom
print('Chi-square statistic: ', chi2)
print('p-value: ', p)
print('Degrees of freedom: ', dof)


Chi-square statistic:  21.851612168613475
p-value:  2.945690038078843e-06
Degrees of freedom:  1


In [19]:
chiSquare=sum([((o-e)**2)/e for o,e in zip(observedValue,expectedValue)])
chiSquare

array([10.62348706, 12.40699218])

In [20]:
chiSquareVal=chiSquare.sum()
chiSquareVal

23.030479240147343

In [24]:
criticalVal=stats.chi2.ppf(q=0.95,df=1)
criticalVal

3.841458820694124

In [26]:
if chiSquareVal>=criticalVal:
  print('Null Hypothesis H0 is rejected, Ha is accepted.')
  print('There is a relationship btw the two categorical column("sex and heartdisease")')
else:
  print('Null Hypothesis H0 is accepted, Ha is rejected.')
  print('There is a no relationship btw the two categorical column("sex and heartdisease")')

Null Hypothesis H0 is rejected, Ha is accepted.
There is a relationship btw the two categorical column("sex and heartdisease")


In [27]:
pval=1-stats.chi2.cdf(x=chiSquareVal,df=1)
pval

1.5945330533728708e-06

In [28]:
if pval<0.05:
  print('Null Hypothesis H0 is rejected, Ha is accepted.')
  print('There is a relationship btw the two categorical column("sex and heartdisease")')
else:
  print('Null Hypothesis H0 is accepted, Ha is rejected.')
  print('There is a no relationship btw the two categorical column("sex and heartdisease")')

Null Hypothesis H0 is rejected, Ha is accepted.
There is a relationship btw the two categorical column("sex and heartdisease")
